export { default as theme } from './theme/index'
export type { ThemeConfig, Sidebar, SidebarItem } from './theme/config'
export { defineThemeConfig } from './theme/config'
export { toOpenGraphLocale } from './shared/i18n'
export { default as Badge } from './theme/components/Badge.vue'
export { default as Comments } from './features/comments/Comments.vue'
export { useCommentsConfig } from './features/comments/config'
export { default as NewsArchiveLinks } from './features/news/NewsArchiveLinks.vue'
export { default as NewsList } from './features/news/NewsList.vue'
export { default as NewsMeta } from './features/news/NewsMeta.vue'
export { default as NewsMetaAuthors } from './features/news/NewsMetaAuthors.vue'
export { default as NewsMetaPublishedAt } from './features/news/NewsMetaPublishedAt.vue'
export { default as NewsMetaStatuses } from './features/news/NewsMetaStatuses.vue'
export { formatNewsLabel, useNewsConfig } from './features/news/config'
